services:
  - type: web
    name: stockapp
    env: python
    buildCommand: |
      cd frontend && npm install && CI=false npm run build
      cp -r build ../frontend/build
      pip install -r backend/requirements.txt
    startCommand: python backend/yfinanceCalls.py
    rootDir: .