services:
  - type: web
    name: stockapp
    env: python
    buildCommand: |
      cd src
      npm install
      npm run build
    startCommand: gunicorn backend.yfinanceCalls:app
    buildFilter:
      paths:
        - src/*
