services:
  - type: web
    name: stockapp
    env: python
    buildCommand: |
      cd frontend && npm install && npm run build
      cp -r frontend/build ./build
      pip install -r backend/requirements.txt
    startCommand: python backend/yfinanceCalls.py
    rootDir: .